### ISSUE TITLE
Unable to run the demo version in 2018

### ISSUE THREAD

**Issue by FaizanZahid** [dwyl/hapi-socketio-redis-chat-example#106]
I am trying to run this but getting following error in my console

D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master>node server.js
D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\node_modules\hapi\node_modules\hoek\lib\index.js:736
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid connection options {
  "compression": true,
  "router": {
    "isCaseSensitive": true,
    "stripTrailingSlash": false
  },
  "routes": {
    "cache": {
      "statuses": [
        200,
        204
      ],
      "otherwise": "no-cache"
    },
    "compression": {},
    "cors": false,
    "files": {
      "relativeTo": "."
    },
    "json": {
      "replacer": null,
      "space": null,
      "suffix": null,
      "escape": false
    },
    "log": false,
    "payload": {
      "failAction": "error",
      "maxBytes": 1048576,
      "output": "data",
      "parse": true,
      "timeout": 10000,
      "uploads": "C:\\Users\\FAIZAN~1\\AppData\\Local\\Temp",
      "defaultContentType": "application/json",
      "compression": {}
    },
    "response": {
      "ranges": true,
      "emptyStatusCode": 200,
      "options": {}
    },
    "security": null,
    "state": {
      "parse": true,
      "failAction": "error"
    },
    "timeout": {
      "server": false
    },
    "validate": {
      "options": {}
    }
  },
  "host": "0.0.0.0",
  "port" [31m[1, 2, 3][0m: NaN
}
[31m
[1] "port" must be a number
[2] "port" must be a string
[3] "port" must be a string[0m
    at Object.exports.unique.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\node_modules\hapi\node_modules\hoek\lib\index.js:736:11)
    at Object.exports.apply (D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\schema.js:17:10)
    at D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\server.js:165:27
    at Array.forEach (native)
    at module.exports.internals.Server.internals.Server._createCache.internals.Server.connection.options [as connection] (D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\server.js:159:24)
    at Object.<anonymous> (D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master\server.js:4:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

D:\work\Ideas Practical\Projects\globalchat\hapi-socketio-redis-chat-example-master>

Can anyone help  or fix pleasE?

**Comment by FaizanZahid** [comment]
Seen the other issues, and i ran npm run local and on my windows i added the port myself in server.js , it worked.
