### ISSUE TITLE
Reply.view error

### ISSUE THREAD

**Issue by crash21** [dwyl/hapi-socketio-redis-chat-example#80]
Hello,

When i start it I get:

    Debug: internal, implementation, error
    TypeError: Uncaught error: reply.view is not a function
    at C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi-error\lib\index.js:153:20
    at each (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\request.js:406:22)
    at iterate (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\node_modules\items\lib\index.js:36:13)
    at Object.exports.serial (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\node_modules\items\lib\index.js:39:9)
    at _protect.run (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\request.js:409:15)
    at internals.Protect.run (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\protect.js:62:12)
    at internals.Request._invoke (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\request.js:389:19)
    at internals.Request._reply (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\request.js:457:17)
    at Items.serial (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\lib\request.js:383:65)
    at done (C:\Wamp\www\hapi-socketio-redis-chat-example\node_modules\hapi\node_modules\items\lib\index.js:31:25)

**Comment by bwang22** [comment]
I got this also when I first started. Make sure you have redis running on your server

**Comment by nelsonic** [comment]
@crash21 could you PR this instruction into the Readme to inform people they need Redis running? thanks!
